name: Publish PHP74 Image

on:
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push PHP74 image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: php-fpm/Dockerfile-PHP74
          push: true
          tags: kjlion/php:7.4-fpm-alpine
          platforms: linux/amd64,linux/arm64
